[workspace]
resolver = "3"

members = [
    "tutorial",
    "version-helper",

    "analytics/analytics",
    "analytics/burn",

    "audio/audiofx",
    "audio/audioparsers",
    "audio/claxon",
    "audio/csound",
    "audio/demucs",
    "audio/elevenlabs",
    "audio/lewton",
    "audio/speechmatics",
    "audio/spotify",
    "audio/whisper",

    "generic/file",
    "generic/originalbuffer",
    "generic/sodium",
    "generic/threadshare",
    "generic/inter",
    "generic/streamgrouper",
    "generic/gopbuffer",

    "mux/flavors",
    "mux/isobmff",

    "net/aws",
    "net/deepgram",
    "net/hlsmultivariantsink",
    "net/hlssink3",
    "net/icecast",
    "net/mpegtslive",
    "net/ndi",
    "net/onvif",
    "net/raptorq",
    "net/reqwest",
    "net/rtp",
    "net/rtsp",
    "net/webrtchttp",
    "net/webrtc",
    "net/webrtc/protocol",
    "net/webrtc/signalling",
    "net/quinn",

    "text/accumulate",
    "text/ahead",
    "text/json",
    "text/regex",
    "text/wrap",

    "utils/fallbackswitch",
    "utils/livesync",
    "utils/debugseimetainserter",
    "utils/togglerecord",
    "utils/tracers",
    "utils/uriplaylistbin",
    "utils/validate",

    "video/cdg",
    "video/closedcaption",
    "video/dav1d",
    "video/ffv1",
    "video/gif",
    "video/gtk4",
    "video/hsv",
    "video/png",
    "video/rav1e",
    "video/skia",
    "video/videofx",
    "video/vvdec",
    "video/webp",
]

# Only plugins without external dependencies
default-members = [
    "version-helper",

    "analytics/analytics",
    "analytics/burn",

    "audio/audioparsers",
    "audio/audiofx",
    "audio/claxon",
    "audio/demucs",
    "audio/lewton",

    "generic/originalbuffer",
    "generic/threadshare",
    "generic/inter",
    "generic/gopbuffer",
    "generic/streamgrouper",

    "mux/isobmff",

    "net/aws",
    "net/mpegtslive",
    "net/hlssink3",
    "net/icecast",
    "net/onvif",
    "net/raptorq",
    "net/reqwest",
    "net/rtp",
    "net/rtsp",
    "net/webrtchttp",
    "net/webrtc",
    "net/webrtc/protocol",
    "net/webrtc/signalling",
    "net/ndi",
    "net/quinn",

    "text/accumulate",
    "text/ahead",
    "text/json",
    "text/regex",
    "text/wrap",

    "utils/fallbackswitch",
    "utils/livesync",
    "utils/debugseimetainserter",
    "utils/togglerecord",
    "utils/tracers",
    "utils/uriplaylistbin",
    "utils/validate",

    "video/cdg",
    "video/ffv1",
    "video/gif",
    "video/hsv",
    "video/png",
    "video/rav1e",
]

[profile.release]
lto = "thin"
codegen-units = 1
opt-level = 3
debug = true
panic = 'unwind'

[profile.dev]
opt-level = 1
lto = "off"

[workspace.package]
version = "0.15.2"
repository = "https://gitlab.freedesktop.org/gstreamer/gst-plugins-rs"
edition = "2024"
rust-version = "1.92"

[workspace.dependencies]
glib = { version = "0.22" }
gio = { version = "0.22" }
cairo-rs = { version = "0.22", features=["use_glib"] }
pango = { version = "0.22" }
pangocairo = { version = "0.22" }
gtk = { package = "gtk4", version = "0.11", features = ["v4_6"]}
gdk-wayland = { package = "gdk4-wayland", version = "0.11", features = ["v4_4"]}
gdk-x11 = { package = "gdk4-x11", version = "0.11", features = ["v4_4"]}
gdk-win32 = { package = "gdk4-win32", version = "0.11", features = ["v4_4"]}
gst = { package = "gstreamer", version = "0.25" }
gst-allocators = { package = "gstreamer-allocators", version = "0.25" }
gst-analytics = { package = "gstreamer-analytics", version = "0.25" }
gst-app = { package = "gstreamer-app", version = "0.25" }
gst-audio = { package = "gstreamer-audio", version = "0.25" }
gst-base = { package = "gstreamer-base", version = "0.25" }
gst-check = { package = "gstreamer-check", version = "0.25" }
gst-gl = { package = "gstreamer-gl", version = "0.25" }
gst-gl-egl = { package = "gstreamer-gl-egl", version = "0.25" }
gst-gl-wayland = { package = "gstreamer-gl-wayland", version = "0.25" }
gst-gl-x11 = { package = "gstreamer-gl-x11", version = "0.25" }
gst-net = { package = "gstreamer-net", version = "0.25" }
gst-pbutils = { package = "gstreamer-pbutils", version = "0.25" }
gst-plugin-version-helper = { version = "0.8" }
gst-rtp = { package = "gstreamer-rtp", version = "0.25" }
gst-sdp = { package = "gstreamer-sdp", version = "0.25" }
gst-tag = { package = "gstreamer-tag", version = "0.25" }
gst-utils = { package = "gstreamer-utils", version = "0.25" }
gst-video = { package = "gstreamer-video", version = "0.25" }
gst-webrtc = { package = "gstreamer-webrtc", version = "0.25" }
gst-plugin-webrtc-protocol = { package = "gst-plugin-webrtc-signalling-protocol", version = "0.15.0" }
gst-plugin-webrtc-signalling = { package = "gst-plugin-webrtc-signalling", version = "0.15.0" }
gst-plugin-rtp = { path="net/rtp", version = "0.15.0" }
